export const PROJECT_SKILL_LIST = [
  { key: "project_management", value: "PjM" },
  { key: "product_management", value: "PdM" },
  { key: "project_management_office", value: "PMO" },
  { key: "project_leader", value: "PL" },
  { key: "chief_technology_officer", value: "CTO" },
  { key: "tech_lead", value: "テックリード" },
];

export const SOFTWHERE_SKILL_LIST = [
  { key: "requirements_definition", value: "要件定義" },
  { key: "basic_design", value: "基本設計" },
  { key: "detailed_design", value: "詳細設計" },
  { key: "frontend_development", value: "フロントエンド" },
  { key: "backend_development", value: "バックエンド" },
  { key: "infrastructure", value: "インフラ" },
  { key: "mobile_development", value: "モバイル開発" },
  { key: "game_development", value: "ゲーム開発" },
  { key: "business_system_development", value: "業務系システム開発" },
  { key: "embedded_development", value: "組み込み開発" },
  { key: "ecommerce_site", value: "ECサイト" },
  { key: "database_design_construction", value: "データベース設計・構築" },
  { key: "big_data", value: "データサイエンス" },
  { key: "vr", value: "VR・AR・XR" },
  { key: "test_design", value: "テスト設計" },
  { key: "quality_assurance", value: "QA" },
  { key: "tester", value: "テスター" },
];

export const PROGRAMMING_SKILL_LIST = [
  { key: "html_css", value: "HTML/CSS" },
  { key: "php", value: "PHP" },
  { key: "ruby", value: "Ruby" },
  { key: "python", value: "Python" },
  { key: "perl", value: "Perl" },
  { key: "javascript", value: "JavaScript" },
  { key: "typescript", value: "TypeScript" },
  { key: "dart", value: "Dart" },
  { key: "swift", value: "Swift" },
  { key: "objective_c", value: "Objective-C" },
  { key: "java", value: "Java" },
  { key: "kotlin", value: "Kotlin" },
  { key: "scala", value: "Scala" },
  { key: "c_sharp", value: "C#" },
  { key: "asp_net", value: "ASP.NET" },
  { key: "c_language", value: "C言語" },
  { key: "go", value: "Go" },
  { key: "rust", value: "Rust" },
  { key: "zig", value: "Zig" },
  { key: "c_plus_plus", value: "C++" },
  { key: "carbon", value: "Carbon" },
  { key: "webassembly", value: "WebAssembly" },
  { key: "erlang", value: "Erlang" },
  { key: "elixir", value: "Elixir" },
  { key: "r", value: "R" },
  { key: "clojure", value: "Clojure" },
  { key: "haskell", value: "Haskell" },
  { key: "vba", value: "VBA" },
  { key: "vbscript", value: "VBScript" },
  { key: "cobol", value: "COBOL" },
  { key: "sql", value: "SQL" },
  { key: "pl_sql", value: "PL/SQL" },
];

export const FRAMEWORK_SKILL_LIST = [
  { key: "laravel", value: "Laravel" },
  { key: "cakephp", value: "CakePHP" },
  { key: "fuelphp", value: "FuelPHP" },
  { key: "symfony", value: "Symfony" },
  { key: "ruby_on_rails", value: "Ruby on Rails" },
  { key: "django", value: "Django" },
  { key: "flask", value: "Flask" },
  { key: "angular", value: "Angular" },
  { key: "react_js", value: "React.js" },
  { key: "next_js", value: "Next.js" },
  { key: "vue_js", value: "Vue.js" },
  { key: "nuxt_js", value: "Nuxt.js" },
  { key: "express_js", value: "Express.js" },
  { key: "nestjs", value: "NestJS" },
  { key: "node_js", value: "Node.js" },
  { key: "deno", value: "deno" },
  { key: "electron", value: "Electron" },
  { key: "flutter", value: "Flutter" },
  { key: "react_native", value: "React Native" },
  { key: "xamarin", value: "Xamarin" },
  { key: "cordova", value: "Cordova" },
  { key: "spring", value: "Spring" },
  { key: "spring_boot", value: "Spring Boot" },
  { key: "struts", value: "Struts" },
  { key: "seasar2", value: "Seasar2" },
  { key: "unity", value: "Unity" },
  { key: "hadoop", value: "Hadoop" },
  { key: "apache_spark", value: "Apache Spark" },
];

export const DATABASE_SKILL_LIST = [
  { key: "oracle", value: "Oracle" },
  { key: "mysql", value: "MySQL" },
  { key: "postgresql", value: "PostgreSQL" },
  { key: "sql_server", value: "SQL Server" },
  { key: "access", value: "Access" },
  { key: "mongodb", value: "MongoDB" },
  { key: "redis", value: "Redis" },
  { key: "cassandra", value: "Cassandra" },
  { key: "sqlite", value: "SQLite" },
  { key: "elasticsearch", value: "Elasticsearch" },
];

export const TOOL_SKILL_LIST = [
  { key: "aws", value: "AWS" },
  { key: "azure", value: "Azure" },
  { key: "gcp", value: "GCP" },
  { key: "wordpress", value: "WordPress" },
  { key: "ansible", value: "Ansible" },
  { key: "chef", value: "Chef" },
  { key: "terraform", value: "Terraform" },
  { key: "jenkins", value: "Jenkins" },
  { key: "docker", value: "Docker" },
  { key: "kubernetes", value: "Kubernetes" },
  { key: "tensorflow", value: "Tensorflow" },
  { key: "firebase", value: "Firebase" },
  { key: "tableau", value: "Tableau" },
  { key: "scikit_learn", value: "scikit-learn" },
  { key: "pytorch", value: "PyTorch" },
  { key: "salesforce", value: "Salesforce" },
  { key: "sap", value: "SAP" },
  { key: "active_directory", value: "Active Directory" },
  { key: "uipath", value: "UiPath" },
];

export const SKILL_LIST = [
  ...PROJECT_SKILL_LIST,
  ...SOFTWHERE_SKILL_LIST,
  ...PROGRAMMING_SKILL_LIST,
  ...FRAMEWORK_SKILL_LIST,
  ...DATABASE_SKILL_LIST,
  ...TOOL_SKILL_LIST,
];
