export { Text } from "@/components/atoms/text";
export { Description } from "@/components/atoms/text/Description";
export { Heading } from "@/components/atoms/heading";
export { Inner } from "@/components/atoms/inner";
export { LinkText } from "@/components/atoms/link/LinkText";
export { Span } from "@/components/atoms/span";
export { Loading } from "@/components/atoms/loading";
export { Button } from "@/components/atoms/button";
export { Link } from "@/components/atoms/link";
export { default as Image } from "next/image";
