name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      # Lint実行: ESLintを使用してソースコードのlintを行います。
      - name: Lint with eslint
        run: npm run lint

      - name: Start Storybook
        run: npm run storybook &
        env:
          CI: true

      - name: Test Storybook
        run: npm run test-storybook

      - name: Test Jest
        run: npm run test-jest

      # # DangerJSの実行: PRでの変更をチェックして、警告やエラーを報告
      # - name: Run Danger JS
      #   uses: danger/danger-js@11.0.2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DANGER_DISABLE_TRANSPILATION: true

      # # ビルド: yarn buildコマンドでアプリケーションをビルド
      # - name: Build
      #   run: npm run build
